# Example:
# https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
keys:
  - &primary age10tfevy6a05qhtvjmhyshaj0hdf8063uhcujy4uq2mz58j4m4k97se6y44y
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *primary
